#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : QDarkStyle
Version  : 2.8.1
Release  : 2
URL      : https://files.pythonhosted.org/packages/83/52/40111409358173b1013231638f58793a4f43f935b8419919b47846d5e0a6/QDarkStyle-2.8.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/83/52/40111409358173b1013231638f58793a4f43f935b8419919b47846d5e0a6/QDarkStyle-2.8.1.tar.gz
Summary  : The most complete dark stylesheet for Python and Qt applications
Group    : Development/Tools
License  : MIT
Requires: QDarkStyle-bin = %{version}-%{release}
Requires: QDarkStyle-license = %{version}-%{release}
Requires: QDarkStyle-python = %{version}-%{release}
Requires: QDarkStyle-python3 = %{version}-%{release}
Requires: QtPy
Requires: helpdev
BuildRequires : QtPy
BuildRequires : buildreq-distutils3
BuildRequires : helpdev

%description
This module provides a function to load the stylesheets transparently
        with the right resources file.
        
        First, start importing our module

%package bin
Summary: bin components for the QDarkStyle package.
Group: Binaries
Requires: QDarkStyle-license = %{version}-%{release}

%description bin
bin components for the QDarkStyle package.


%package license
Summary: license components for the QDarkStyle package.
Group: Default

%description license
license components for the QDarkStyle package.


%package python
Summary: python components for the QDarkStyle package.
Group: Default
Requires: QDarkStyle-python3 = %{version}-%{release}
Provides: qdarkstyle-python

%description python
python components for the QDarkStyle package.


%package python3
Summary: python3 components for the QDarkStyle package.
Group: Default
Requires: python3-core
Provides: pypi(qdarkstyle)
Requires: pypi(helpdev)
Requires: pypi(qtpy)

%description python3
python3 components for the QDarkStyle package.


%prep
%setup -q -n QDarkStyle-2.8.1
cd %{_builddir}/QDarkStyle-2.8.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1596132022
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/QDarkStyle
cp %{_builddir}/QDarkStyle-2.8.1/LICENSE.rst %{buildroot}/usr/share/package-licenses/QDarkStyle/5d123fa18608e0752be8d4fb7cabf5526894fe00
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qdarkstyle

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/QDarkStyle/5d123fa18608e0752be8d4fb7cabf5526894fe00

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
